project:
  type: website
  
lang: en
mainfont: "HarmonyOS Sans SC"

website:
  title: ""
  navbar:
    background: primary
    left:
      - text: Home
        href: index.qmd
      - text: People
        href: People.qmd
      - text: Publication
        href: Publication.qmd
      - text: 中文简历
        href: AboutCN.qmd
    right:
      - text: 博客
        href: Blog.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
