project:
  type: website
  
lang: en
mainfont: "HarmonyOS Sans SC"

website:
  favicon: assets/logo-2023-12-18.svg
  title: ""
  navbar:
    background: primary
    logo: assets/logo-2023-12-18.png
    left:
      - text: Home
        href: index.qmd
      - text: People
        href: people.qmd
      - text: Publication
        href: publication.qmd
      - text: Blog
        href: blog.qmd
    right:
      - text: 简历
        href: about_cn.qmd
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
