---
editor: visual
csl: "Systematic Biology"
---

# 2023

-   Wang Y., Li W., **Li X.**, Yang D. 2023. Two new species of the subfamily Mydaeinae (Diptera: Muscidae) from China. Zootaxa. 5318:543--554.

-   Cai X.-D., **Li X.**, Cao W.-Q., Yang D. 2023. Two new species of the genus *Norellisoma* Wahlgren, 1917 (Diptera, Scathophagidae) from Yintiaoling Nature Reserve, Chongqing, China. Zookeys. 1168:151--159.

-   **Li X.**, Wiens J.J. 2023. Estimating global biodiversity: the role of cryptic insect species. Syst. Biol. 72:391--403.

-   **Li X.**, Cai X., Ding S., Wang L., Li W., Liu X., Zhang C., Yang D. 2023. Phylogeny and evolutionary timescale of Muscidae (Diptera: Calyptratae) inferred from mitochondrial genomes. Insects. 14:286.

# 2022

-   **Li X.**, Wang L., Yang D. 2022. The complete mitochondrial genome of *Ornithomya biloba* (Diptera, Hippoboscidae). Mitochondrial DNA Part B. 7:856--858.

-   **李新** (作者): 刺股蝇科. 杨定, 姚刚等 (2022). 浙江昆虫志第九卷双翅目短角亚目, 北京: 科学出版社, 1--402 + 24图版.

# 2020

-   **Li X.**, Zhou J., Wang L., Hou P., Yang D. 2020. The mitochondrial genome of *Prosthiochaeta* sp. (Diptera: Platystomatidae). Mitochondrial DNA Part B. 5:2557--2558.

-   **李新** (编委, 作者) (2020). 中国生物物种名录. 昆虫. 双翅目. 短角亚目. 蝇类, 北京: 科学出版社, 1--1331.

# 2019

-   **Li X.**, Wang L., Li Z., Hou P., Yang D. 2019. The mitochondrial genome of *Formicosepsis* sp. (Diptera: Cypselosomatidae). Mitochondrial DNA Part B. 4:2140--2141.

# 2016

-   **李新** (编委, 作者): 寄蝇亚科, 追寄蝇亚科部分, 总论, 图版部分. 张春田等 (2016). 东北地区寄蝇科昆虫, 北京: 科学出版社, 1--698 + 14 图版.
